---
title: Learning in visual regions as support for the bias in future value-driven choice
author: |
  | Sara Jahfari ^[Corresponding author: sara.jahfari@gmail.com] $^{1,2}$, Jan Theeuwes $^3$, Tomas Knapen $^{1,3}$
  |
  | $^1$	Spinoza Centre for Neuroimaging, Royal Netherlands Academy of Arts and Sciences (KNAW), The Netherlands,  $^2$	Department of Psychology, University of Amsterdam, The Netherlands, $^3$ Department of Experimental and Applied Psychology, Vrije Universiteit van Amsterdam, The Netherlands

#output: github_document
output:
  pdf_document:
    fig_width: 6
    fig_height: 4
    fig_caption: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Supplementary

![**BOLD and the modulation of $\Delta$Value in the learning phase for cortical regions.** The top row shows the FIR-estimated BOLD signal time-course, time-locked to the presentation of AB (red lines), CD (green lines), and EF (blue lines) face pairs for the additional cortical regions that were evaluated with RF (b). The bottom row displays the differential modulation by value ($\Delta$Value = modulation Q chosen – modulation Q unchosen). The horizontal lines show the interval in which the modulation was significantly stronger for Q chosen. With the presentation of AB faces, only the BOLD responses in M1 was modulated more by values of the chosen stimulus when com-pared to values of the unchosen stimulus. Confidence intervals were estimated using bootstrap analysis across participants (n=1000), where the shaded region represents the standard error of the mean across participants (i.e. bootstrapped 68% confidence interval).  ](_png/sFigure1.png)


![**Reward prediction errors and BOLD during the learning phase in cortical regions.** The top row shows the FIR-estimated BOLD signal time-course, which was time-locked to the presenta-tion of choice feedback, shown for the additional cortical regions evaluated with RF. The bottom row displays modulations of the estimated BOLD time-course by singed (green lines), or unsigned (orange lines) RPEs. The horizontal lines represent the interval in which singed or unsigned RPEs contributed significantly to the modulation of BOLD in the multiple regression. Note that, both variables were always evaluated simultaneously in one GLM. \label{sFigure 2}](_png/sFigure2.png)


![**Uncertainty and Ranking of RF evaluated for all participants.** a) Plotted relationship between the uncertainty of the forest in each prediction (x-axis) and delta value (y-axis) for all partici-pants. Delta value was computed for each transfer-phase trial using the end beliefs that partici-pants had about stimuli at the end of the learning phase. Forest uncertainty is defined as the pro-portion of trees saying ‘yes! the choice on this trial was optimal’. When this ratio is bellow 0.5 the forest will predict ‘no’ (sub-optimal), otherwise the prediction is ‘yes! the choice on this trial was optimal’ (optimal). $R^2$=adjusted $R^2$. d) Plotted ranking of the ROI’s in their contribution to the predictive accuracy of RF evaluated with all participants.\label{sFigure 3}](_png/sFigure3.png)
